# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  mainProject: '**/Principal.Telemedicine.Shared.Configuration.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: 'Build Configuration project'
  inputs:
    command: 'build'
    projects: '$(mainProject)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script'
  inputs:
    azureSubscription: 'pipelines-wetnow'
    ScriptType: 'InlineScript'
    Inline: |
      # Přihlášení identitou do Azure
      $resourceGroupName = 'VetNOW'
      $keyVaultName = 'kv-wetnow-dev'
      $identityName = 'VetNowPipelineUami'
      
      $identity = Get-AzUserAssignedIdentity -ResourceGroupName $resourceGroupName -Name $identityName
      Login-AzAccount -Identity $identity
- task: DotNetCoreCLI@2
  displayName: 'Run xUnit Tests'
  inputs:
    command: 'custom'
    custom: 'test'
    projects: '**/Principal.Telemedicine.Shared.Configuration.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
    buildProperties: 

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package for main project'
  inputs:
    command: 'pack'
    packagesToPack: '$(mainProject)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'Telemedicína/Telemedicine'
    allowPackageConflicts: true