trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

steps:
- script: nuget restore
  displayName: 'Restore NuGet packages'

- task: VSBuild@1
  inputs:
    solution: 'Principal.Telemedicine/Principal.Telemedicine.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    msbuildArgs: '/p:OutputPath=$(Build.ArtifactStagingDirectory)\BuildOutput'
  displayName: 'Build solution'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.ArtifactStagingDirectory)\BuildOutput\Principal.Telemedicine.Shared.Logging.dll'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'
    includeSymbols: true
  displayName: 'Create NuGet package for Principal.Telemedicine.Shared.Logging'

- task: NuGetAuthenticate@0
  displayName: 'Authenticate NuGet feed'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Telemedicine'
    includeSymbols: true
  displayName: 'Push NuGet package to Artefact Feed'
