# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: '**/Principal.Telemedicine.Shared.Logging.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Run xUnit Tests'
  inputs:
    command: 'custom'
    custom: 'test'
    projects: '**/*.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
    buildProperties: 
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: Principal.Telemedicine.Shared.Logging
    
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    versioningScheme: 'off'
    outputDir: '$(Build.ArtifactStagingDirectory)'

# NuGet authenticate v1
# Configure NuGet tools to authenticate with Azure Artifacts and other NuGet repositories. Requires NuGet >= 4.8.5385, dotnet >= 6, or MSBuild >= 15.8.166.59604.
- task: NuGetAuthenticate@1
  #inputs:
    #nuGetServiceConnections: # string. Service connection credentials for feeds outside this organization. 
    #forceRe

- task: NuGetCommand@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Telemedicine' # Název feedu, kam chceme publikovat balíček
    allowPackageConflicts: true