# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  mainProject: '**/Principal.Telemedicine.Shared.Configuration.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: $[variables['Ref-Configuration.Major']]
  Minor: $[variables['Ref-Configuration.Minor']]
  Patch: $[variables['Ref-Configuration.Patch']]
  steps:
    - script: echo $(Major)
    - script: echo $(Minor)
    - script: echo $(Patch)
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for solutions include Telemedicine feed'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'Telemedicína/Telemedicine'
    includeNuGetOrg: true
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: 'Build $(mainProject)'
  inputs:
    command: 'build'
    projects: '$(mainProject)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'

- powershell: |
    Write-Host "##vso[task.setvariable variable=ASPNETCORE_ENVIRONMEN]development"
    $Env:ASPNETCORE_ENVIRONMENT = "development"
  displayName: 'Set EnvironmentName variable'
  
- task: DotNetCoreCLI@2
  displayName: 'Run xUnit Tests'
  inputs:
    command: 'custom'
    custom: 'test'
    projects: '**/Principal.Telemedicine.Shared.Configuration.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
    buildProperties: 

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package for $(mainProject)'
  inputs:
    command: 'pack'
    packagesToPack: '$(mainProject)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    outputDir: '$(Build.ArtifactStagingDirectory)'



- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'Telemedicína/Telemedicine'
    allowPackageConflicts: true