trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- script: nuget restore
  displayName: 'Restore NuGet packages'

- task: VSBuild@1
  inputs:
    solution: 'Principal.Telemedicine/Principal.Telemedicine.sln'  # Upravte cestu k vašemu solution (soubor .sln)
    platform: 'Any CPU'
    configuration: 'Release'
  displayName: 'Build solution'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Principal.Telemedicine/Principal.Telemedicine.Shared.Logging/Principal.Telemedicine.Shared.Logging.csproj'  # Upravte cestu k vašemu csproj souboru
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'
    includeSymbols: true
    buildProperties: 'Configuration=Release'
  displayName: 'Create NuGet package for Principal.Telemedicine.Shared.Logging'

- task: NuGetAuthenticate@0
  displayName: 'Authenticate NuGet feed'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Telemedicine'  # Nahraďte názvem svého Artefact Feedu
    includeSymbols: true
  displayName: 'Push NuGet package to Artefact Feed'
