# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Ref-Shared
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
 
  
  
steps:
- script: echo 'Verze $(Major).$(Minor).$(Patch)'
  displayName: 'Installed version'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for solutions include Telemedicine feed'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'Telemedicína/Telemedicine'
    includeNuGetOrg: true
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: 'Build $(mainProject)'
  inputs:
    command: 'build'
    projects: '$(mainProject)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'

  

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package for $(mainProject)'
  inputs:
    command: 'pack'
    packagesToPack: '$(mainProject)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    outputDir: '$(Build.ArtifactStagingDirectory)'



- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'Telemedicína/Telemedicine'
    allowPackageConflicts: true