# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  mainProject: '**/Principal.Telemedicine.Shared.Logging.csproj'
  sharedProject: '**/Principal.Telemedicine.Shared.csproj'
  dataConnectorsProject: '**/Principal.Telemedicine.DataConnectors.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'Telemedicine'
    nugetConfigPath: 'https://pkgs.dev.azure.com/principaltelemedicina/21ebfe7b-2f4d-4d46-9319-1caf04ec83b6/_packaging/Telemedicine/nuget/v3/index.json'
    includeNuGetOrg: true
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: 'Build main project'
  inputs:
    command: 'build'
    projects: '$(mainProject)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
- task: DotNetCoreCLI@2
  displayName: 'Build shared project'
  inputs:
    command: 'build'
    projects: '$(sharedProject)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Build data connectors project'
  inputs:
    command: 'build'
    projects: '$(dataConnectorsProject)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Run xUnit Tests'
  inputs:
    command: 'custom'
    custom: 'test'
    projects: '**/Principal.Telemedicine.Shared.Logging.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
    buildProperties: 

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package for main project'
  inputs:
    command: 'pack'
    packagesToPack: '$(mainProject)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    outputDir: '$(Build.ArtifactStagingDirectory)\Logging'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package for data shared project'
  inputs:
    command: 'pack'
    packagesToPack: '$(sharedProject)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    outputDir: '$(Build.ArtifactStagingDirectory)\Shared'
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package for data connectors project'
  inputs:
    command: 'pack'
    packagesToPack: '$(dataConnectorsProject)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    outputDir: '$(Build.ArtifactStagingDirectory)\Data'
- task: PowerShell@2
  displayName: 'Copy DLLs from DataConnectors and shared project to main project'
  inputs:
    targetType: 'inline'
    script: |
      $sharedDLLPath = "$(Build.ArtifactStagingDirectory)\Shared\Principal.Telemedicine.Shared.*.nupkg"
      $fileList = Get-ChildItem -Path $sharedDLLPath -File
      Write-Host "Seznam souborů shared projektu $sharedDLLPath"
      foreach ($file in $fileList) {
      Write-Host "Název souboru: $($file.Name)"
      }
      $dataConnectorsDLLPath = "$(Build.ArtifactStagingDirectory)\Data\Principal.Telemedicine.DataConnectors.*.nupkg"
      $fileList = Get-ChildItem -Path $dataConnectorsDLLPath -File
      Write-Host "Seznam souborů connectors projektu $dataConnectorsDLLPath"
      foreach ($file in $fileList) {
      Write-Host "Název souboru: $($file.Name)"
      }
      $mainProjectDLLPath = "$(Build.ArtifactStagingDirectory)\Logging\Principal.Telemedicine.Shared.Logging.*.nupkg"
      $fileList = Get-ChildItem -Path $mainProjectDLLPath -File
      Write-Host "Seznam souborů main projektu $mainProjectDLLPath"
      foreach ($file in $fileList) {
      Write-Host "Název souboru: $($file.Name)"
      }
      Expand-Archive -Path $sharedDLLPath -DestinationPath $(Build.ArtifactStagingDirectory)\SharedPackage    
      Expand-Archive -Path $dataConnectorsDLLPath -DestinationPath $(Build.ArtifactStagingDirectory)\DataConnectorsPackage
      Expand-Archive -Path $mainProjectDLLPath -DestinationPath $(Build.ArtifactStagingDirectory)\MainProjectPackage
      $sharedDLLFiles = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)\SharedPackage" -Recurse -Filter "*.dll"
      $dataConnectorsDLLFiles = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)\DataConnectorsPackage" -Recurse -Filter "*.dll"
      $mainProjectDLLFiles = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)\MainProjectPackage" -Recurse -Filter "*.dll"

    
    
      Copy-Item $sharedDLLFiles -Destination "$(Build.ArtifactStagingDirectory)\MainProjectPackage"
      Copy-Item $dataConnectorsDLLFiles -Destination "$(Build.ArtifactStagingDirectory)\MainProjectPackage"
      
      Compress-Archive -Path "$(Build.ArtifactStagingDirectory)\MainProjectPackage\*" -DestinationPath "$(Build.ArtifactStagingDirectory)\MergedPackage.zip"


- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/MainProjectPackage/*.nupkg'
    publishVstsFeed: 'Telemedicína/Telemedicine'
    allowPackageConflicts: true